# Generated by Django 5.0.1 on 2024-01-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='stock',
            field=models.BooleanField(default=True),
        ),
    ]
