# Generated by Django 5.0.1 on 2024-01-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_alter_cartitem_options_food_suggested'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='desplay',
            field=models.BooleanField(default=False),
        ),
    ]
