# Generated by Django 5.0.1 on 2024-01-08 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_new_desplay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='desplay',
            new_name='display',
        ),
    ]
