# Generated by Django 5.0.1 on 2024-01-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
