# Generated by Django 5.0.1 on 2024-01-08 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_alter_order_total_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-order_number'], 'verbose_name': 'คำสั่งซื้อ', 'verbose_name_plural': 'รายการคำสั่งซื้อ'},
        ),
    ]
