# Generated by Django 5.0.1 on 2024-01-08 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_remove_order_id_alter_order_order_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
