# Generated by Django 5.0.1 on 2024-01-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
