# Generated by Django 5.0.1 on 2024-01-08 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0022_cart_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
    ]
