# Generated by Django 5.0.1 on 2024-01-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0024_cart_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='order_items', to='members.cartitem'),
        ),
    ]
